"""empty message

Revision ID: 155ba02e6150
Revises: 7ed41ef5a084
Create Date: 2018-11-11 01:08:51.242288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '155ba02e6150'
down_revision = '7ed41ef5a084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loser_id', sa.Text(), nullable=False),
    sa.Column('winner_id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['cat.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['cat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('loser_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('winner_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['loser_id'], ['cat.id'], name='match_loser_id_fkey'),
    sa.ForeignKeyConstraint(['winner_id'], ['cat.id'], name='match_winner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='match_pkey')
    )
    op.drop_table('vote')
    # ### end Alembic commands ###
